# Generated by Django 2.2.1 on 2019-12-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='predicciones.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='predicciones.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('codigo', models.CharField(max_length=150, unique=True)),
                ('inscritos', models.IntegerField()),
                ('cc', models.IntegerField(default=0)),
                ('fpv', models.IntegerField(default=0)),
                ('mts', models.IntegerField(default=0)),
                ('ucs', models.IntegerField(default=0)),
                ('mas', models.IntegerField(default=0)),
                ('v1f', models.IntegerField(default=0)),
                ('pdc', models.IntegerField(default=0)),
                ('mnr', models.IntegerField(default=0)),
                ('panbol', models.IntegerField(default=0)),
                ('validos', models.IntegerField(default=0)),
                ('blancos', models.IntegerField(default=0)),
                ('nulos', models.IntegerField(default=0)),
                ('trep', models.BooleanField()),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='predicciones.Recinto')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='predicciones.Pais'),
        ),
    ]
